Repository NVIDIA/modulus-launch, pull requests merged in 2023-07, with the labels that each got.

#46 23.08 Release preparation
  CHANGELOG.md
  Dockerfile
  pyproject.toml
Labels: 3 - Ready for Review, ! - Release

#45 remove accompanying licenses
  accompanying_licenses/all_licenses.txt
  accompanying_licenses/explanation.txt
Labels: 5 - Ready to Merge, ! - Release

#56 Adjustments to Github Templates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/documentation_request.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: enhancement, 3 - Ready for Review

#62 vortex shedding download script
  CHANGELOG.md
  examples/cfd/vortex_shedding_mgn/raw_dataset/download_dataset.sh
Labels: bug, 3 - Ready for Review

#67 update default configs
  CHANGELOG.md
  examples/weather/fcn_sfno/config/cos_zenith_sfnonet.yaml
  examples/weather/fcn_sfno/config/sfnonet.yaml
  examples/weather/fcn_sfno/train.py
Labels: bug

#36 Fix batch size in inference
  examples/cfd/vortex_shedding_mgn/inference.py
Labels: bug, 3 - Ready for Review

#68 Adding standard python exempts to gitignore
  .gitignore
Labels: enhancement, ci

#69 update vortex shedding inference
  examples/cfd/ahmed_body_mgn/inference.py
  examples/cfd/ahmed_body_mgn/train.py
  examples/cfd/vortex_shedding_mgn/inference.py
  examples/weather/graphcast/constants.py
Labels: enhancement, 3 - Ready for Review, ! - Release

#61 fea-ext-ignore_.gitignore_paths_in_header_test
  .gitignore
  CHANGELOG.md
  test/ci_tests/header_check.py
Labels: 3 - Ready for Review, ci

#51 fix: Checkpoint update
  CHANGELOG.md
  modulus/launch/utils/checkpoint.py
  pyproject.toml
Labels: bug, 3 - Ready for Review, ! - Release
