Repository NVIDIA/modulus-launch, pull requests merged in 2023-08, with the labels that each got.

#72 Version update 0.2.0
  .github/ISSUE_TEMPLATE/bug_report.yml
  CHANGELOG.md
  modulus/launch/__init__.py
  pyproject.toml
Labels: 3 - Ready for Review, ! - Release

#42 fixed checkpoints
  examples/cfd/darcy_fno/train_fno_darcy.py
  examples/cfd/darcy_nested_fnos/evaluate_nested_darcy.py
  examples/cfd/darcy_nested_fnos/train_nested_darcy.py
  modulus/launch/utils/checkpoint.py
Labels: enhancement, 2 - In Progress, 5 - DO NOT MERGE

#87 add the missing denormalization of the pressure
  examples/cfd/vortex_shedding_mgn/inference.py
Labels: bug

#99 Replaced torch.norm to torch.linalg.norm to attempt to fix issue #77
  examples/cfd/ahmed_body_mgn/utils.py
  examples/cfd/gray_scott_rnn/gray_scott_rnn.py
  examples/cfd/navier_stokes_rnn/navier_stokes_rnn.py
  examples/weather/fcn_sfno/models.py
  examples/weather/fcn_sfno/trainer.py
Labels: external
