Repository NVIDIA/modulus-launch, pull requests merged in 2023-09, with the labels that each got.

#105 Version update 0.3.0
  .github/ISSUE_TEMPLATE/bug_report.yml
  CHANGELOG.md
  modulus/launch/__init__.py
  pyproject.toml
Labels: ! - Release

#95 Add example for 1D simulation of blood flow dynamics
  .gitignore
  CHANGELOG.md
  docs/img/bloodflow_1d_mgn_geometries.png
  docs/img/bloodflow_1d_mgn_results.gif
  examples/healthcare/bloodflow_1d_mgn/README.md
  examples/healthcare/bloodflow_1d_mgn/config.yaml
  examples/healthcare/bloodflow_1d_mgn/generate_dataset.py
  examples/healthcare/bloodflow_1d_mgn/generate_graphs.py
  examples/healthcare/bloodflow_1d_mgn/graph_tools.py
  examples/healthcare/bloodflow_1d_mgn/inference.py
  examples/healthcare/bloodflow_1d_mgn/raw_dataset/download_dataset.sh
  examples/healthcare/bloodflow_1d_mgn/train.py
  examples/healthcare/bloodflow_1d_mgn/vtk_tools.py
  test/ci_tests/header_check.py
Labels: enhancement, 3 - Ready for Review

#101 Enh ext ahmed body loss
  examples/cfd/ahmed_body_mgn/constants.py
  examples/cfd/ahmed_body_mgn/train.py
  examples/cfd/ahmed_body_mgn/utils.py
Labels: 3 - Ready for Review

#111 Fixes an issue when no scaler is given, but it is present in the checkpoint
  CHANGELOG.md
  modulus/launch/utils/checkpoint.py
Labels: bug, 5 - Ready to Merge

#104 ERA5 Mirror
  CHANGELOG.md
  examples/weather/dataset_download/README.md
  examples/weather/dataset_download/conf/config_34var.yaml
  examples/weather/dataset_download/conf/config_tas.yaml
  examples/weather/dataset_download/era5_mirror.py
  examples/weather/dataset_download/start_mirror.py
Labels: enhancement, 4 - In Review
